import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { MapPin, Sparkles, Star, ArrowRight, Globe, Brain, Compass, Users, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import HeroSlider from "@/components/HeroSlider";
import { useLanguage } from "@/contexts/LanguageContext";
import heroBg from "@/assets/hero-bg.jpg";
import { allDestinations } from "@/data/destinations";
import AiVoyagerDashboard from "@/components/ai-voyager/AiVoyagerDashboard";

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.5, ease: [0.25, 0.46, 0.45, 0.94] as const },
  }),
};

const reviews = [
  { name: "Sarah M.", text: "The AI trip planner created an amazing itinerary for our family vacation in Malaysia. Every recommendation was spot on!", rating: 5, type: "Destination" },
  { name: "Ahmad R.", text: "Incredible platform! The chatbot helped me find hidden gems in Penang I never would have discovered on my own.", rating: 5, type: "Attraction" },
  { name: "Lisa T.", text: "Budget-friendly suggestions that actually worked. Saved 30% on our honeymoon trip!", rating: 4, type: "Travel Type" },
];

const features = [
  { icon: Brain, title: "AI-Powered Planning", desc: "Get personalized day-by-day travel itineraries generated by AI" },
  { icon: Globe, title: "Smart Destinations", desc: "Explore destinations with AI-curated descriptions and insights" },
  { icon: Compass, title: "Activity Discovery", desc: "Find activities matched to your interests and fitness level" },
  { icon: MessageCircle, title: "AI Chatbot", desc: "Ask questions and get instant travel recommendations" },
];

const Index = () => {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${heroBg})` }} />
        <div className="absolute inset-0 bg-hero-overlay" />
        <div className="absolute inset-0 opacity-10" style={{
          backgroundImage: `radial-gradient(circle at 25% 25%, hsl(174, 62%, 46%) 1px, transparent 1px), radial-gradient(circle at 75% 75%, hsl(174, 62%, 46%) 1px, transparent 1px)`,
          backgroundSize: "60px 60px",
        }} />

        <div className="relative z-10 container mx-auto px-4 text-center">
          <motion.div initial="hidden" animate="visible" className="max-w-4xl mx-auto">
            <motion.div custom={0} variants={fadeUp} className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-card mb-6">
              <Sparkles className="w-4 h-4 text-coral" />
              <span className="text-sm font-medium text-foreground/90">{t("hero.badge")}</span>
            </motion.div>
            <motion.h1 custom={1} variants={fadeUp} className="text-4xl md:text-6xl lg:text-7xl font-display font-bold text-gradient-hero leading-tight mb-6">
              {t("hero.title")}
            </motion.h1>
            <motion.p custom={2} variants={fadeUp} className="text-lg md:text-xl text-foreground/80 max-w-2xl mx-auto mb-10 leading-relaxed" style={{color:"white"}}>
              {t("hero.desc")}
            </motion.p>
            <motion.div custom={3} variants={fadeUp} className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Button variant="hero" size="lg" className="text-base px-8 py-6" style={{color:"white"}} asChild>
                <Link to="/plan"><MapPin className="w-5 h-5" style={{color:"white"}} />{t("hero.plan")}</Link>
              </Button>
              <Button variant="hero-outline" size="lg" className="text-base px-8 py-6" style={{color:"white"}} asChild>
                <Link to="/contact"><Sparkles className="w-5 h-5"  style={{color:"white"}}/>{t("hero.chat")}</Link>
              </Button>
            </motion.div>
          </motion.div>
        </div>

        <motion.div className="absolute bottom-8 left-1/2 -translate-x-1/2" animate={{ y: [0, 8, 0] }} transition={{ repeat: Infinity, duration: 2 }}>
          <div className="w-6 h-10 rounded-full border-2 border-primary-foreground/30 flex justify-center pt-2">
            <div className="w-1 h-2 rounded-full bg-primary-foreground/50" />
          </div>
        </motion.div>
      </section>

      <AiVoyagerDashboard context="home" />

      {/* Features */}
      <section className="section-padding bg-background" id="about">
        <div className="container mx-auto">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-100px" }} className="text-center mb-16">
            <motion.h2 custom={0} variants={fadeUp} className="text-3xl md:text-4xl font-display font-bold text-foreground mb-4">
              {t("about.title").split(",")[0]}, <span className="text-gradient-teal">{t("about.title").split(",")[1] || "Simplified"}</span>
            </motion.h2>
            <motion.p custom={1} variants={fadeUp} className="text-muted-foreground max-w-2xl mx-auto">{t("about.desc")}</motion.p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, i) => (
              <motion.div key={feature.title} initial="hidden" whileInView="visible" viewport={{ once: true }} custom={i} variants={fadeUp}
                className="bg-card rounded-xl p-6 shadow-[var(--shadow-card)] card-lift border border-border">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-display font-semibold text-card-foreground mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{feature.desc}</p>
              </motion.div>
            ))}
          </div>

          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} className="mt-20 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div custom={0} variants={fadeUp}>
              <h3 className="text-2xl md:text-3xl font-display font-bold text-foreground mb-6">About Our Project</h3>
              <div className="space-y-4 text-muted-foreground leading-relaxed">
                <p><strong className="text-foreground">{t("about.vision")}</strong> {t("about.vision.text")}</p>
                <p><strong className="text-foreground">{t("about.tech")}</strong> {t("about.tech.text")}</p>
                <p><strong className="text-foreground">{t("about.future")}</strong> {t("about.future.text")}</p>
              </div>
            </motion.div>
            <motion.div custom={1} variants={fadeUp} className="grid grid-cols-2 gap-4">
              {[{ number: "50+", label: "Destinations" }, { number: "10K+", label: "Happy Travelers" }, { number: "AI", label: "Powered Plans" }, { number: "24/7", label: "Chatbot Support" }].map((stat) => (
                <div key={stat.label} className="bg-card rounded-xl p-6 text-center shadow-[var(--shadow-card)] border border-border">
                  <div className="text-2xl md:text-3xl font-display font-bold text-primary mb-1">{stat.number}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Popular Destinations */}
      <section className="section-padding bg-secondary/50">
        <div className="container mx-auto">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} className="flex items-end justify-between mb-10">
            <div>
              <motion.h2 custom={0} variants={fadeUp} className="text-3xl md:text-4xl font-display font-bold text-foreground mb-2">{t("popular")}</motion.h2>
              <motion.p custom={1} variants={fadeUp} className="text-muted-foreground">{t("popular.desc")}</motion.p>
            </div>
            <motion.div custom={2} variants={fadeUp}>
              <Button variant="ghost" asChild><Link to="/destinations">{t("view.all")} <ArrowRight className="w-4 h-4" /></Link></Button>
            </motion.div>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-5">
            {allDestinations.map((dest, i) => (
              <motion.div key={dest.id} initial="hidden" whileInView="visible" viewport={{ once: true }} custom={i} variants={fadeUp}>
                <Link to={`/destinations/${dest.id}`} className="group block">
                  <div className="relative rounded-xl overflow-hidden card-lift shadow-[var(--shadow-card)]">
                    <img src={dest.image} alt={dest.name} className="w-full h-56 object-cover group-hover:scale-105 transition-transform duration-500" />
                    <div className="absolute inset-0 bg-gradient-to-t from-foreground/70 via-transparent to-transparent" />
                    <div className="absolute bottom-0 left-0 right-0 p-4">
                      <span className="inline-block px-2 py-0.5 rounded-full bg-primary/90 text-primary-foreground text-xs font-medium mb-2">{dest.category}</span>
                      <h3 className="font-display font-semibold text-primary-foreground">{dest.name}</h3>
                      <div className="flex items-center gap-1 mt-1">
                        <Star className="w-3.5 h-3.5 text-coral fill-coral" />
                        <span className="text-sm text-primary-foreground/80">{dest.rating}</span>
                      </div>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <HeroSlider contained />

      {/* Reviews */}
      <section className="section-padding bg-background">
        <div className="container mx-auto">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} className="text-center mb-12">
            <motion.h2 custom={0} variants={fadeUp} className="text-3xl md:text-4xl font-display font-bold text-foreground mb-4">{t("reviews.title")}</motion.h2>
          </motion.div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {reviews.map((review, i) => (
              <motion.div key={review.name} initial="hidden" whileInView="visible" viewport={{ once: true }} custom={i} variants={fadeUp}
                className="bg-card rounded-xl p-6 shadow-[var(--shadow-card)] border border-border card-lift">
                <div className="flex items-center gap-1 mb-3">
                  {Array.from({ length: review.rating }).map((_, j) => (
                    <Star key={j} className="w-4 h-4 text-coral fill-coral" />
                  ))}
                </div>
                <span className="inline-block px-2 py-0.5 rounded-full bg-primary/10 text-primary text-xs font-medium mb-3">{review.type}</span>
                <p className="text-card-foreground text-sm leading-relaxed mb-4">"{review.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center"><Users className="w-4 h-4 text-primary" /></div>
                  <span className="font-medium text-sm text-card-foreground">{review.name}</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* About Us */}
      <section className="section-padding bg-background">
        <div className="container mx-auto">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }} className="max-w-4xl mx-auto">
            <motion.h2 custom={0} variants={fadeUp} className="text-3xl md:text-4xl font-display font-bold text-foreground mb-4 text-center">
              About Us
            </motion.h2>
            <motion.p custom={1} variants={fadeUp} className="text-muted-foreground leading-relaxed text-center">
              Ai Voyager Guide is a smart digital tourism platform that provides integrated, AI-driven trip planning and personalized travel services. We bring discovery, planning, and travel support into one experience—so you can go from “Where should I go?” to “I’m ready” faster. Our recommendations are tailored to your style, budget, and pace, helping you feel confident at every step.
            </motion.p>

            <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
              <motion.div custom={2} variants={fadeUp} className="bg-card rounded-xl p-6 shadow-[var(--shadow-card)] border border-border">
                <h3 className="font-display font-semibold text-card-foreground mb-2">Our Mission</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Our mission is to help travelers plan with confidence through personalization and simplicity. We use AI to understand what matters to you—interests, time, budget, and travel preferences—and translate it into actionable trip plans. By reducing guesswork and decision fatigue, we give you more time to focus on what travel should be: excitement, comfort, and discovery.
                </p>
              </motion.div>

              <motion.div custom={3} variants={fadeUp} className="bg-card rounded-xl p-6 shadow-[var(--shadow-card)] border border-border">
                <h3 className="font-display font-semibold text-card-foreground mb-2">Our Vision</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  We envision a future where travel planning feels effortless and truly personalized for everyone. Ai Voyager Guide aims to be the platform travelers rely on for smart recommendations, seamless planning, and end-to-end support. Our vision is tourism powered by intelligence, designed around humans.
                </p>
              </motion.div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="relative section-padding overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-ocean-deep via-primary to-ocean-mid" />
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: `radial-gradient(circle, hsl(0, 0%, 100%) 1px, transparent 1px)`, backgroundSize: "40px 40px" }} />
        <div className="relative z-10 container mx-auto text-center">
          <motion.div initial="hidden" whileInView="visible" viewport={{ once: true }}>
            <motion.h2 custom={0} variants={fadeUp} className="text-3xl md:text-4xl font-display font-bold text-primary-foreground mb-4">{t("cta.title")}</motion.h2>
            <motion.p custom={1} variants={fadeUp} className="text-primary-foreground/70 max-w-xl mx-auto mb-8">{t("cta.desc")}</motion.p>
            <motion.div custom={2} variants={fadeUp}>
              <Button variant="coral" size="lg" className="text-base px-8 py-6" asChild>
                <Link to="/plan">{t("cta.btn")} <ArrowRight className="w-5 h-5" /></Link>
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Index;
